### ISSUE TITLE
Incorrect behaviour of TSO CLI.

### ISSUE THREAD

**Issue by VKrus** [zowe/zowe-explorer-intellij#143] opened 2023-08-03 14:24 UTC
I can't normally execute RACF commands in TSO CLI. When opening the console, the first command seems to be executed, while at first I get the message Ready, and then the command seems to be executed a second time (without any action from my side), and, of course, it fails. For example, this is the show case for DELUSER command.
![image](https://github.com/zowe/zowe-explorer-intellij/assets/78022375/f44a8b9c-c353-485d-a959-3b3752b97c8a)
Firstly I got message Ready, that identifies successful execution of first command, but than I got INVALID USERID. And I think it is because of the fact that the plugin tries to send same command second time, and it fails, because the user is no longer there (a similar problem for ADDUSER). And when you try to execute commands further (not even RACF commands), then nothing works anymore, as if it sends a message to enter a new operand, and it constantly starts saying INVALID USERID.
![image](https://github.com/zowe/zowe-explorer-intellij/assets/78022375/ee9b8ecc-b6d6-4c16-b5d6-043ab0f8b839)

**Steps To Reproduce**
1. Create TSO console;
2. Execute ADDUSER TSTUSER1;
![image](https://github.com/zowe/zowe-explorer-intellij/assets/78022375/ecc3a609-0344-47c5-9fe5-84f21ed22156)
3. Try to send any more command.
![image](https://github.com/zowe/zowe-explorer-intellij/assets/78022375/31196b22-2455-4f17-bc41-6d0864d258f6)

**Comment by KUGDev** [comment] 2023-10-20 10:10
Closing as the issue is not reproducible

**Closed** 2023-11-23 15:13 UTC
Labels: bug, priority-medium, severity-medium
